export const vars = {
  'spacer': 0,
  'minmax': null,
  'prefix': null,
  'xxs': 0,
  'xs': 0,
  'sm': 0,
  'md': 0,
  'lg': 0,
  'xl': 0,
  'xxl': 0,
  'dev': false,
  'modal-transition-time': null,
  'color-primary': null,
  'color-secondary': null,
  'color-tertiary': null,
  'color-text': null,
  'color-link': null,
  'color-info': null,
  'color-success': null,
  'color-warning': null,
  'color-danger': null
}
